postgresql:
  imageName: mattiasgees/spiffe-postgres
  imageTag: latest

spiffe:
  socketPath: /spiffe-workload-api/socket
  trustdomain: spire.internal.mattiasgees.be

spiffeHelper:
  imageName:  mattiasgees/spiffe-helper
  imageTag: latest

spiffeApp:
  imageName: mattiasgees/spiffe-demo
  imageTag: latest

initContainer:
  imageName: mattiasgees/spiffe-demo-init
  imageTag: latest
  awsRoleArn: arn:aws:iam::228615251467:role/demo-spiffe-role
  JWTAudience: demo

gcpProxy:
  gcpProjectName: GCP_PROJECT_NAME
  gcpProjectNumber: GCP_PROJECT_NUMBER

spiffeCustomer:
  awsRegion: eu-west-2
  s3Bucket: BUCKET_NAME
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hostname: DEMO_HOSTNAME

spiffeCustomerRogue:
  hostname: DEMO_ROGUE_HOSTNAME
