postgresql:
  imageName: ghcr.io/mattiasgees/spiffe-demo/spiffe-postgres
  imageTag: latest

spiffe:
  socketPath: /spiffe-workload-api/socket
  trustdomain: spire.internal.mattiasgees.be

spiffeHelper:
  imageName:  ghcr.io/mattiasgees/spiffe-demo/spiffe-helper
  imageTag: latest

spiffeApp:
  imageName: ghcr.io/mattiasgees/spiffe-demo/spiffe-demo
  imageTag: latest

initContainer:
  imageName: ghcr.io/mattiasgees/spiffe-demo/spiffe-demo-init
  imageTag: latest
  awsRoleArn: AWS_ROLE_ARN
  awsTrustAnchorArn: AWS_TRUST_ANCHOR_ARN
  awsProfileArn: AWS_PROFILE_ARN
  awsAuth: AWS_AUTH
  JWTAudience: demo

spiffeGcpProxy:
  imageName: ghcr.io/mattiasgees/spiffe-demo/spiffe-gcp-proxy
  imageTag: latest
  gcpProjectName: GCP_PROJECT_NAME
  gcpProjectNumber: "GCP_PROJECT_NUMBER"

spiffeCustomer:
  awsRegion: eu-west-2
  s3Bucket: BUCKET_NAME
  gcpBucket: GCP_BUCKET_NAME
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hostname: DEMO_HOSTNAME

spiffeCustomerRogue:
  hostname: DEMO_ROGUE_HOSTNAME
