apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spiffeDemo.name" . }}-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spiffeDemo.name" . }}-backend
  labels:
    app: spiffe-backend
spec:
  selector:
    matchLabels:
      app: spiffe-backend
  template:
    metadata:
      labels:
        app: spiffe-backend
    spec:
      serviceAccountName: {{ include "spiffeDemo.name" . }}-backend
      containers:
        - name: spiffe-backend
          image: "{{- .Values.spiffeApp.imageName -}}:{{- .Values.spiffeApp.imageTag -}}"
          imagePullPolicy: Always
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          args:
          - backend
          - --authorized-spiffe
          - "spiffe://{{- .Values.spiffe.trustdomain -}}/ns/{{- .Release.Namespace -}}/sa/{{- include "spiffeDemo.name" . -}}-customer"
          - --server-address
          - 0.0.0.0:8443
          env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: "unix://{{- .Values.spiffe.socketPath -}}"
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
      volumes:
      - csi:
          driver: csi.spiffe.io
          readOnly: true
        name: spiffe-workload-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiffeDemo.name" . }}-backend
spec:
  selector:
    app: spiffe-backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
