apiVersion: v1
kind: ServiceAccount
metadata:
  name: spiffe-customer
  namespace: spiffe-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spiffe-customer
  namespace: spiffe-demo
  labels:
    app: spiffe-customer
spec:
  selector:
    matchLabels:
      app: spiffe-customer
  template:
    metadata:
      labels:
        app: spiffe-customer
    spec:
      serviceAccountName: spiffe-customer
      containers:
        - name: spiffe-customer
          image: mattiasgees/spiffe-demo@sha256:6f75051ac72782da8d4fe9bf28d85274ddb1116e3567fa1ca715f5c28db59ee8
          imagePullPolicy: Always
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          args:
          - customer
          - --authorized-spiffe
          - "spiffe://spire.internal.mattiasgees.be/ns/spiffe-demo/sa/spiffe-backend"
          - --server-address
          - 0.0.0.0:8080
          - --socket-path
          - unix:///spiffe-workload-api/socket
          - --backend-service
          - https://spiffe-backend.spiffe-demo.svc.cluster.local
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
      volumes:
      - csi:
          driver: csi.spiffe.io
          readOnly: true
        name: spiffe-workload-api
---
apiVersion: v1
kind: Service
metadata:
  name: spiffe-customer
  namespace: spiffe-demo
spec:
  selector:
    app: spiffe-customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-signin: https://login.mattias-gcp.jetstacker.net/oauth2/start?rd=https://$host$request_uri$is_args$args
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.authentication.svc.cluster.local/oauth2/auth
  name: spiffe-customer
  namespace: spiffe-demo
spec:
  rules:
  - host: spiffe-demo.mattias-gcp.jetstacker.net
    http:
      paths:
      - backend:
          service:
            name: spiffe-customer
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - spiffe-demo.mattias-gcp.jetstacker.net
    secretName: spiffe-demo
