global:
  spire:
    clusterName: democluster
    trustDomain: spire.demo.com
    jwtIssuer: https://OIDC_HOSTNAME
    recommendations:
      enabled: false
    namespaces:
      create: false
    strictMode: true

spire-server:
  ca_subject:
    country: UK
    organization: Demo
    common_name: spire.demo.com
  controllerManager:
    enabled: true
    identities:
      clusterSPIFFEIDs:
        default:
          autoPopulateDNSNames: true

spiffe-oidc-discovery-provider:
  tls:
    spire:
      enabled: false
  enabled: true
  insecureScheme:
    enabled: true
  agentSocketName: socket
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - host: OIDC_HOSTNAME
      paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: oidc-backend-tls
      hosts:
        - OIDC_HOSTNAME

spire-agent:
  # This socket path is a requirement for Istio https://istio.io/latest/docs/ops/integrations/spire/
  socketPath: "/run/secrets/workload-spiffe-uds/socket"
  workloadAttestors:
    k8s:
      skipKubeletVerification: false
      disableContainerSelectors: false

# This socket path is a requirement for Istio https://istio.io/latest/docs/ops/integrations/spire/
spiffe-csi-driver:
  agentSocketPath: "/run/secrets/workload-spiffe-uds/socket"
