name: Docker Images

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push spiffe-demo
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: mattiasgees/spiffe-demo:latest

      - name: Build and push spiffe-demo init
        uses: docker/build-push-action@v6
        with:
            platforms: linux/amd64,linux/arm64
            push: true
            context: ./deploy/initcontainer
            tags: mattiasgees/spiffe-demo-init:latest

      - name: Build and push spiffe-postgres
        uses: docker/build-push-action@v6
        with:
            platforms: linux/amd64,linux/arm64
            push: true
            context: ./deploy/postgresql
            tags: mattiasgees/spiffe-postgres:latest

      - name: Build and push spiffe-helper
        uses: docker/build-push-action@v6
        with:
            platforms: linux/amd64,linux/arm64
            push: true
            context: ./deploy/spiffe-helper
            tags: mattiasgees/spiffe-helper:latest