name: Docker Image SPIFFE GCP Proxy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push spiffe-gcp-proxy
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./deploy/spiffe-gcp-proxy
          tags: mattiasgees/spiffe-demo:${{ github.event_name == 'pull_request' && github.head_ref || 'latest' }}
