name: Docker Image SPIFFE GCP Proxy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: set lower case owner name
        run: |
          echo "REPOSITORY=${REPOSITORY_NN,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY_NN: '${{ github.repository }}'

      - name: Build and push spiffe-gcp-proxy
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./deploy/spiffe-gcp-proxy
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/spiffe-gcp-proxy:${{ github.event_name == 'pull_request' && github.head_ref || 'latest' }}
